0xPolygon/cdk-data-availability

synchronizer/batches.go
synchronizer/reorg.go
test/Makefile

This PR fixes the ReorgDetector's Stop method so that it closes the subscriber channels. It also applies some minor refactoring.

Close subscribers

---

sequence/sequence.go

When performing the string based comparison for two hexadecimal values (in this case while forming the signature for a requested sequence with data committee member private key), the logic does not consider the fact that the ` Bytes2Hex` function returns output in lowercase char. for the hexadecimal string.
While performing comparison with `7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0` using the lower case string it gives wrong results for most of the cases. This is because the ASCII values of upper case and lower case char. are different, which is what is considered while performing the string based comparison.
LHS (hash): `7a9d59c0b984259000bfbb7787965552e85f6b84f8a85461fc8fc050cc47ab41`
RHS: `7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0`
```go
if …
```

Fix comparison while creating signatures

---

go.sum
synchronizer/batches.go

This PR fixes the error logging on the batch synchronizer. The log was not showing the error, only the batch payload. This will help diagnose errors faster.

log error instead of batches

---

synchronizer/batches.go
synchronizer/rpc.go
synchronizer/store.go
test/config/test.dev.toml
test/config/test.docker.toml
test/e2e/datacommittee_test.go

This PR fixes case where batch size is not supplied, fixes a bug with storing sync_info, and simplifies the filter workers.
It also introduces a late comer in the DAC test, which turns on after the transactions are mined, and catches up by getting data from other DAC members.
- the test still seems a bit flakey, maybe with timing? 
- the test generates a tx with a key, but no value, but that comes from the cdk-validium-node test operations

Synchro fix

---

db/db.go
db/migrations/0003.sql
go.mod
synchronizer/batches.go
synchronizer/store.go
test/Makefile
test/stop-dacs

This PR adds a new table for sync_tasks that stores the last block named tasks have processed, and removes the old sync_info table, which stored a block reference for each block batch processed/scanned. This is better for storage, and will allow other block scanner tasks to use the same pattern and table in the future if required. The SQL is also simplified.

Storage optimized sync tracking

---

cmd/main.go
synchronizer/init.go
test/Makefile
test/e2e/datacommittee_test.go

This PR adds an initialization step that finds the inception block of the CDKValidium contract and sets the start block for the L1 sync task. It skips the search if the start block is already set.

Init L1 sync task

---

.github/workflows/release.yml
.goreleaser.yml
Dockerfile.release
LICENSE

The PR introduces goreleaser for building and publishing releases for CDK DAC repo. It builds binaries for the predefined platforms and builds and pushes Docker images to the Docker Hub (https://hub.docker.com/r/0xpolygon/cdk-data-availability).

Introduce `release` github workflow

---

config/config.go
config/default.go
synchronizer/init.go

Synchronizer can avoid the init routine of finding the block where contract is deployed on L1 if GenesisBlock number is provided in the config file

Added genesis block of L1 contract to DAC config

---

db/db.go
db/db_test.go
db/migrations/0004.sql
mocks/db.generated.go
synchronizer/batches.go
synchronizer/batches_test.go
synchronizer/store.go
synchronizer/store_test.go
types/types.go

The logic is going to be the following:
- Get batches from the incoming event.
- Store batches into "unresolved_batches" table.
- Get records from "unresolved_batches" table.
- Filter really unresolved batches by checking the hash in "offchain_data" table.
- Delete existing (resolved) batches from "unresolved_batches" table if exists. It might happen in theory.
- Resolve unresolved bathes.
- Delete resolved batches from "unresolved_batches" table.

DAC batch resolver resilience improvement

---

config/config.go
config/default.go
docs/running.md
sequencer/tracker.go
sequencer/tracker_test.go
test/config/test.dev.toml
test/config/test.docker.toml
test/config/test.local.toml

Make the trackers that track url and addr config changes optional. Retain the initial lookup of the values, but optionally turn off the websocket event tracking.
This can help the gelato situation where they have flakey ws support, and don’t need the feature for now anyway.

Make DAC ws config tracking optional

---

cmd/main.go
etherman/etherman.go
mocks/etherman.generated.go
pkg/backoff/backoff.go
pkg/backoff/backoff_test.go
sequencer/tracker.go
sequencer/tracker_test.go
services/datacom/datacom_test.go
test/e2e/sequencer_tracker_test.go

Added a maximum number of connection retries to the sequencer tracker. If the number of attempts is exceeded, the app is going to crash.

Added max connection retries number to the sequencer tracker

---

config/config.go
config/default.go
docs/running.md
sequencer/tracker.go
sequencer/tracker_test.go
test/config/test.dev.toml
test/config/test.docker.toml
test/config/test.local.toml

This PR back ports the "tracker optional" feature to release/v0.0.6

Make DAC ws config tracking optional (#64)

---

cmd/main.go
version.go

The PR introduces version metadata information dump at the app startup.
For example:
```go
Starting application...
Version:      v0.0.7-19-gf9a61b2
Git revision: f9a61b2
Git branch:   feat/include-version-info-to-logs
Go version:   go1.19.13
Built:        Sun, 28 Apr 2024 09:02:03 +0000
OS/Arch:      linux/amd64
```

Include version info in the logs at the app startup

---

.github/workflows/regression-tests.yml

What does this PR do?
performs automatic regression detection checks when new code changes are proposed for 'main' branch. specifically, behind the scenes, we spin up a lightweight cdk devnet (via k8s and kurtosis, fully within git action runner) and test a containerized version of the proposed code changes to ensure network operation and block production is sound under load tests and some bake time
Tests
run successfully within CI layer, as seen here: https://github.com/rebelArtists/agglayer/actions/runs/9008640654/job/24751163034

feature: regression tests automatic CI check

---

db/db.go
db/db_test.go
mocks/db.generated.go
synchronizer/batches_test.go
synchronizer/init.go
synchronizer/store.go
synchronizer/store_test.go

We've found that the unprocessed keys table can fill up fairly fast (depending on activity), and the unprocessed batch key handler selects _all_ keys in that table every time it processes them. 
In a production environment, we found the unprocessed table >15k keys, and the processor tries to insert all of them at once, failing due to timeout, and not accumulating resolved data. 
This PR adds a limit (of 100) to the unprocessed sql query. This allows the synchronization to proceed as expected.

Limit number of keys to process simultaneously

---

synchronizer/batches.go
test/e2e/datacommittee_test.go

This PR fixes the issue found by audit, where a race condition can happen while handling reorgs in the `batchSyncronizer` when a new sequence of batches is being synced.
Since both routines update the start block from which we sync batches, it may happen that reorg detector will update the start block while the sync routine is downloading batches, which can lead to some inconsistent batches.
PR introduces a `sync` lock which both routines will use, meaning, we will not handle reorg until we finish syncing batches, or we will not sync batches, until we handle a reorg first.

[Audit remediation] Issue B: Race Condition Between FilterSequenceBatches and handleReorgs

---

synchronizer/batches.go
synchronizer/batches_test.go
synchronizer/committee_map.go
synchronizer/committee_map_test.go

This PR is continuation of #94 and it introduces thread-safe wrapper around the committee members map, allowing for thread-safe manipulation.

Introduce thread-safe committee map to the `synchronizer`

---

db/db.go
db/db_test.go
db/migrations/0005.sql
mocks/db.generated.go
mocks/sequencer_tracker.generated.go
sequencer/call.go
sequencer/call_test.go
sequencer/tracker.go
services/status/status.go
services/sync/sync.go
services/sync/sync_test.go
synchronizer/batches.go
synchronizer/batches_test.go
synchronizer/init.go
synchronizer/init_test.go
synchronizer/store.go
synchronizer/store_test.go
types/types.go

- Added migration for adding `batch_num` column to `offchain_data` table.
- The migration resets the last block number for L1 task in order to trigger resync process that will updated batch number in all existing records. 
- Updated DB layer logic to handle a new field. 
- Updated `handleUnresolvedBatches` function to populate a batch number field 
- It also populates a batch number field for existing records. This is needed to updated batch number in all existing records.

[Audit remediation] Suggestion 1: Adopt a Verifiable Database / Batch Format

---

.golangci.yml
client/client_test.go
config/config.go
db/db_test.go
log/config.go
log/log.go
rpc/client_test.go
rpc/error.go
rpc/handler.go
rpc/server.go
rpc/server_test.go
sequencer/call_test.go
services/datacom/datacom.go
services/datacom/datacom_test.go
services/status/status_test.go
services/sync/sync_test.go
synchronizer/batches.go
synchronizer/batches_test.go
synchronizer/committee_map.go
synchronizer/init.go
synchronizer/init_test.go
synchronizer/store_test.go
synchronizer/util.go

Jira Ticket [here](https://polygon.atlassian.net/browse/CDK-313)

Add Linters

---

types/interfaces.go
types/sequence.go
types/sequence_test.go
types/sequencebanana.go
types/sequencebanana_test.go

Closes #107 
Add next method to interface `SignedSequenceInterface`:
```
SetSignature([]byte)
GetSignature() []byte
```

add Set and Get for Signature of types SignedSequence

---

.github/actions/monitor-cdk-verified-batches/action.yml
.github/actions/monitor-cdk-verified-batches/batch_verification_monitor.sh
.github/workflows/regression-tests.yml
.gitignore
client/client_test.go
cmd/main.go
config/config_test.go
rpc/client_test.go
rpc/server.go
sequencer/tracker.go
services/datacom/datacom_test.go
services/sync/sync_test.go
synchronizer/reorg.go

Adding more UTs to different packages and fixing regression tests by using latest `kurtosis-cdk` changes.

More UTs and fix regression tests

---

go.mod
go.sum
synchronizer/batches.go
synchronizer/util.go
synchronizer/util_test.go

Add support to syncing senqueceBatchesValidium for Banana
Version `0.0.9` is reporting this error: 
```
2024-09-12T14:41:31.687Z ERROR synchronizer/batches.go:231 failed to handle event: unrecognized method id: 165e8a8d 
```

Add synchronization for banana sequences

---

.golangci.yml
rpc/handler.go
rpc/types.go
services/datacom/datacom.go
services/status/status.go
services/status/status_test.go
services/sync/sync.go

When there is a successful response on the certain RPC function, the `error` field (with nil value) is present in the JSON response. This causes issue with Foundry, when trying to deserialize it.
```bash
Deserialization Error: invalid type: null, expected struct JsonRpcError at line 1 column 140. 
Response: {"jsonrpc":"2.0","id":1,"result":{"uptime":"6.547542578s","version":"v0.0.10-15-g5089d5c","key_count":0,"backfill_progress":94},"error":null}
```
The same applies when there is an error, in that case, the response object should be omitted, instead of populating it with the `nil` value.

RPC omit errors when empty

---

client/client.go
client/client_test.go
docs/running.md

Hello
I found several spelling issues in your docs.
Br, Elias.

chore: fix spelling issues

---

.github/workflows/test-unit.yml
config/default.go
db/config.go

This PR adds `SSLMode` configuration. It can be set to "require", "verify-full", "verify-ca", and "disable" with "disable" as default (the current behavior).
The request was to remove the sslmode parameter, where the underlying connection defaults to "require" as default. However, this PR is less intrusive to other deployment upgrades that do not require it currently.
The requester should add `SSLMode` = "require" (or whatever is needed) to the DB section of configuration file.

Allow ssl mode to be configured
